### ISSUE TITLE
code available?

### ISSUE THREAD

**Issue by IgorYbema** [KlausLi/Esp-Seplos-Controller#1]
Hi,
Can you make the code public available?
I have a Seplos BMS connected to a Sofar inverter and using Sofar2MQTT (https://github.com/cmcgerty/Sofar2mqtt) already to read the inverter. I would like to combine the sofar and your seplos code together on one wemos controller.

**Comment by gerdluthe** [comment]
Ich würde mich dem anschliessen und auch fragen ob der Code veröffentlich wird.
Geniales Tool, funktioniert einwandfrei.

**Comment by IgorYbema** [comment]
Why close without answer or solution?

**Comment by KlausLi** [comment]
> Why close without answer or solution?

sorry code not  for free

**Comment by IgorYbema** [comment]
Are you sure you aren't using GPL open source licensed code in your project which requires you to publish your code also? Could be in violation then.
