### ISSUE TITLE
Modbus

### ISSUE THREAD

**Issue by gerdluthe** [KlausLi/Esp-Seplos-Controller#4]
Hallo,

OK Sourcecode wird nicht veröffentlich, das habe ich wohl daraus verstanden, das der Topic mit der Frage danach geschlossen wurde.

Wäre es denn möglich zumindest den Part zu veröffentlichen, der die Kommunikation mit dem BMS betrifft, mir schwebt hier in Verbindung mit dem Victron Multiplus ein Fakemeter vor, das auch die Einzelzellspannungen der Batterien anzeigen kann.

Das würde die Arbeit erleichtern, sich jetzt mit dem Protokoll von Seplos auseinanderzusetzen, wenn das hier schon getan worden ist.

Was ich ansonsten als gutes Feature ansehen würde ist die Möglichkeit, das Intervall mit dem per MQTT die Werte an den Broker gesendet werden, verändern zu können. Einmal / Sekunde ist heftig viel.

Danke für ein Feedback

**Comment by KlausLi** [comment]
der code ist nicht kostenlos zu haben 
Falls interesse beseht bitte ernsthaftes ANGEBOT an meine Email , zu ersehen unter Kanalinfo auf  emienm YT KanaL
